/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.2.0.18.0
    Soft IP Version: 1.0.1
    2023 11 15 23:21:16
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module sysclk_pll (ref_clk_i, rst_n_i, outcore_o, outglobal_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ref_clk_i;
    input  rst_n_i;
    output  outcore_o;
    output  outglobal_o;
endmodule