# Configuration Options
theme: minima
title: Snake through 32x24 1-bit color resolution VGA graphics card
description: "This is the documentation for Kaitlin Lucio and Diego Herrera Vicioso's final project in E155. This page is broken into three subpages, FPGA, MCU, and schematics. Enjoy!"

header-pages:
  - documentation.html
  - resources.html


# Github Pages settings that cannot be changed
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
